# Generated by Django 4.2.1 on 2023-05-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='Category',
            new_name='category',
        ),
    ]
