# Generated by Django 4.2.1 on 2023-06-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_is_customer_user_is_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
